apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-multicontainer-deployment
  namespace: default
  labels:
    app: fastapi-multicontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-multicontainer
  template:
    metadata:
      labels:
        app: fastapi-multicontainer
    spec:
      containers:
      - name: fastapi
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        ports:
        - containerPort: 80
      - name: redis
        image: redis:6
        ports:
        - containerPort: 6379
