apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
data:
  example-key-1: example-value-1
  example-key-2: example-value-2
  example-ini-file: |
    key1=value1
    key2=value2
  example-yaml-file: |
    key1: value1
    key2: value2
    key3:
      key4: value4
      key5: value5

---

apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
  file.txt: |
    ZmlsZSBjb250ZW50cwo=
