apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
data:
  example-key-1: example-value-1
  example-key-2: example-value-2
  example-ini-file: |
    key1=value1
    key2=value2
  example-yaml-file: |
    key1: value1
    key2: value2
    key3:
      key4: value4
      key5: value5

---

apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
  file.txt: |
    ZmlsZSBjb250ZW50cwo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: default
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      volumes:
      - name: example-volume-1
        configMap:
          name: example-configmap
          items:
          - key: example-ini-file
            path: config.ini
      - name: example-volume-2
        secret:
          secretName: example-secret
          items:
          - key: file.txt
            path: config.txt
      containers:
      - name: fastapi
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        ports:
        - containerPort: 80
        env:
        - name: TEST_ENV_1
          value: env_value_1
        - name: TEST_ENV_2
          value: env_value_2
        - name: CONFIG_ENV_1
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: example-key-1
        - name: CONFIG_SECRET_1
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: username
        envFrom:
        - secretRef:
            name: example-secret
        - configMapRef:
            name: example-configmap
        volumeMounts:
        - name: example-volume-1
          mountPath: /etc/example-mount-1
          readOnly: true
        - name: example-volume-2
          mountPath: /etc/example-mount-2
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
